### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by kenculate** [wanmeihuali/taichi_3d_gaussian_splatting#118]
I am trying to run just the visualizer, and facing these error

python visualizer.py --parquet_path_list boots_19000.parquet

[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.10.11
C:\Users\saeid\source\repos\taichi_3d_gaussian_splatting\taichi_3d_gaussian_splatting\GaussianPointCloudScene.py:6: DeprecationWarning: Please use `cKDTree` from the `scipy.spatial` namespace, the `scipy.spatial.ckdtree` namespace is deprecated.
  from scipy.spatial.ckdtree import cKDTree
Traceback (most recent call last):
  File "C:\Users\saeid\source\repos\taichi_3d_gaussian_splatting\visualizer.py", line 23, in <module>
    class GaussianPointVisualizer:
  File "C:\Users\saeid\source\repos\taichi_3d_gaussian_splatting\visualizer.py", line 25, in GaussianPointVisualizer
    class GaussianPointVisualizerConfig:
  File "C:\Users\saeid\source\repos\taichi_3d_gaussian_splatting\visualizer.py", line 29, in GaussianPointVisualizerConfig
    camera_intrinsics: torch.Tensor = torch.tensor(
  File "C:\Users\saeid\source\repos\taichi_3d_gaussian_splatting\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by wanmeihuali** [comment]
Please install torch with CUDA... e.g. 
```
conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.7 -c pytorch -c nvidia
```
please also ensure your cuda version is correct.
